Repository SRGSSR/pillarbox-android, pull requests merged in 2024-05, with the labels that each got.

#524 Separate TimeRanges are it is a sealed interface and we don't really …
  pillarbox-core-business/src/main/java/ch/srgssr/pillarbox/core/business/source/SRGAssetLoader.kt
  pillarbox-core-business/src/test/java/ch/srgssr/pillarbox/core/business/SRGAssetLoaderTest.kt
  pillarbox-player/src/main/java/ch/srgssr/pillarbox/player/asset/Asset.kt
  pillarbox-player/src/main/java/ch/srgssr/pillarbox/player/source/PillarboxMediaSource.kt
  pillarbox-player/src/test/java/ch/srgssr/pillarbox/player/tracker/BlockedTimeRangeTrackerTest.kt
  pillarbox-player/src/test/java/ch/srgssr/pillarbox/player/tracker/ChapterTrackerTest.kt
Labels: enhancement

#526 Make the Dependency Analysis plugin only fails for unused dependencies
  .github/workflows/build.yml
  build.gradle.kts
  gradle.properties
Labels: enhancement

#527 Fix urn name in the demo
  pillarbox-demo-shared/src/main/java/ch/srgssr/pillarbox/demo/shared/data/DemoItem.kt
Labels: bug

#529 Integrate Dokka
  build-logic/plugins/src/main/java/ch/srgssr/pillarbox/gradle/PillarboxAndroidLibraryPublishingPlugin.kt
  build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
Labels: bug

#534 Update guide to setup the GitHub repository
  docs/README.md
Labels: documentation

#539 Custom blocked segments
  pillarbox-demo-shared/src/main/java/ch/srgssr/pillarbox/demo/shared/data/Playlist.kt
  pillarbox-demo-shared/src/main/java/ch/srgssr/pillarbox/demo/shared/di/PlayerModule.kt
  pillarbox-demo-shared/src/main/java/ch/srgssr/pillarbox/demo/shared/source/BlockedTimeRangeAssetLoader.kt
  pillarbox-player/src/main/java/ch/srgssr/pillarbox/player/tracker/TimeRangeTracker.kt
Labels: enhancement
